### ISSUE TITLE
Update Identity Provider profiles for keycloak tasks

### ISSUE THREAD

**Issue by rawc0der** [redkubes/otomi-tasks#17]
# User story
Update keycloak tasks to support Identity Provider profiles with configurable claims & mapper objects

# Tasks

otomi-tasks:
- [ ] Create configurable variables for user details mappers (use oid->username for registration "from azure")

otomi-core:
- [ ] Update relevant env variables for gotmpl files

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are added to code
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified
